### ISSUE TITLE
4 items from template failed preprocessing rule

### ISSUE THREAD

**Issue by Jonmccombs** [v-zhuravlev/zbx_template_apache2#1]
There are Conn async closing, Conn async keep alive, connection async writing, Connection total all fail in Zabbix 4. Error at top of error message is "Item preprocessing step #1 failed: cannot perform regular expression match: pattern does not match, type "string", value "HTTP/1.1 200 OK"

**Comment by TheKnossos** [comment]
I have the same issue in 4.0 but haven't found a solution yet.

**Comment by Jonmccombs** [comment]
Looking at server-status I did not see the key Async so I figured since it was not there the script  could not pull data for it. Is there a server-status argument that needs to be included? Thanks for responding.

**Comment by miksonx** [comment]
As per documentation async info is available under mpm_event
https://httpd.apache.org/docs/trunk/mod/event.html
try 
a2enmod mpm_event 

Be aware that might get in conflict with mpm_worker if enabled
a2dismod worker 

but check what your application/web will serving so not to miss functionality described in (worker
Multi-Processing Module implementing a hybrid multi-threaded multi-process web server)
Tested the check is working.

**Comment by rvalitov** [comment]
Indeed, these items are intended for _MPM event_ only. For other types of MPM these values do not exist.

@Jonmccombs check what MPM is at your Apache, I suspect it's _prefork_. In this case you can just ignore these warnings, and disable these items manually at the host configuration.

**Comment by v-zhuravlev** [comment]
Hello.

These Apache templates are now part of official Zabbix distribution, please use them instead if you have Zabbix 4.2 or later:

HTTP agent template:
https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/app/apache_http
Zabbix agent template:
https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/app/apache_agent

In new templates, MPM event metrics are part of LLD discovery and only available if MPM event is enabled.
