### ISSUE TITLE
Could not get apache status 

### ISSUE THREAD

**Issue by nembulus** [v-zhuravlev/zbx_template_apache2#2]
1. Failed: cannot perform regular expression "ConnsAsyncWriting:\s+([0-9]+)" match for value of type "string": pattern does not match
   936:20190608:144759.587 error reason for "thor:apache2_conns_total" changed: Preprocessing failed for: HTTP/1.0 404 Not Found..Date: Sat, 08 Jun 2019 07:47:58 GMT..Server: Apache..Cache-Control: no-ca...
1. Failed: cannot perform regular expression "ConnsTotal:\s+([0-9]+)" match for value of type "string": pattern does not match
   936:20190608:144759.588 error reason for "thor:apache2_requests_rps" changed: Preprocessing failed for: HTTP/1.0 404 Not Found..Date: Sat, 08 Jun 2019 07:47:58 GMT..Server: Apache..Cache-Control: no-ca...
1. Failed: cannot perform regular expression "ReqPerSec:\s+([0-9\.]+)" match for value of type "string": pattern does not match
   936:20190608:144759.588 error reason for "thor:apache2_total_accesses" changed: Preprocessing failed for: HTTP/1.0 404 Not Found..Date: Sat, 08 Jun 2019 07:47:58 GMT..Server: Apache..Cache-Control: no-ca...
1. Failed: cannot perform regular expression "Total Accesses:\s+([0-9]+)" match for value of type "string": pattern does not match
   936:20190608:144759.588 error reason for "thor:apache2_uptime" changed: Preprocessing failed for: HTTP/1.0 404 Not Found..Date: Sat, 08 Jun 2019 07:47:58 GMT..Server: Apache..Cache-Control: no-ca...
1. Failed: cannot perform regular expression "\bUptime:\s+([0-9.]+)" match for value of type "string": pattern does not match
   936:20190608:144759.588 error reason for "thor:apache2_version" changed: Preprocessing failed for: HTTP/1.0 404 Not Found..Date: Sat, 08 Jun 2019 07:47:58 GMT..Server: Apache..Cache-Control: no-ca...
1. Failed: cannot perform regular expression "ServerVersion:\s+(.+)" match for value of type "string": pattern does not match
   936:20190608:144759.589 error reason for "thor:apache2_workers_busy" changed: Preprocessing failed for: HTTP/1.0 404 Not Found..Date: Sat, 08 Jun 2019 07:47:58 GMT..Server: Apache..Cache-Control: no-ca...
1. Failed: cannot perform regular expression "BusyWorkers:\s+([0-9]+)" match for value of type "string": pattern does not match
   936:20190608:144759.589 error reason for "thor:apache2_workers_idle" changed: Preprocessing failed for: HTTP/1.0 404 Not Found..Date: Sat, 08 Jun 2019 07:47:58 GMT..Server: Apache..Cache-Control: no-ca...
1. Failed: cannot perform regular expression "IdleWorkers:\s+([0-9]+)" match for value of type "string": pattern does not match
   936:20190608:144759.589 error reason for "thor:apache2_Bps" changed: Preprocessing failed for: HTTP/1.0 404 Not Found..Date: Sat, 08 Jun 2019 07:47:58 GMT..Server: Apache..Cache-Control: no-ca...
1. Failed: cannot perform regular expression "BytesPerSec:\s+([0-9\.]+)" match for value of type "string": pattern does not match

Is there any clue for this ?

**Comment by rvalitov** [comment]
Such errors happen when mod_status is not enabled in Apache. You should enable mod_status first. Then you can try to test if it works via console:
```
apache2ctl status
```

If you see a status output, then it's OK and it will work in Zabbix, too.
