### ISSUE TITLE
Documentation suggestion: more detail on setup

### ISSUE THREAD

**Issue by AndyA** [v-zhuravlev/zbx_template_apache2#3]
I've imported the agent template but I'm not seeing any data from it or any requests to /server-status?auto. 

/server-status?auto works fine with curl.

I'm just getting started with Zabbix so I guess that's because I don't understand how to set it up. If anyone can give me a clue I'll happy submit a PR for the README to better document the process.

Thanks :)

**Comment by altmas5** [comment]
Hi @AndyA 

I think it is because the HTTP status code is 302 (redirect) instead of 200 when browsing to `server-status?auto`. From my server log:
```
"GET /server-status?auto HTTP/1.1" 302
```
and the Template is expecting a 200 status code:
```
{myserver.com:apache2_get_server_status.str("HTTP/1.1 200")}=0
```

**Comment by v-zhuravlev** [comment]
Hello.

These Apache templates are now part of official Zabbix distribution with issue mentioned here fixed (for HTTP version of template), please use them instead if you have Zabbix 4.2 or later:

HTTP agent template:
https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/app/apache_http
Zabbix agent template:
https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/app/apache_agent
