### ISSUE TITLE
Requests per second and bytes per second are wrong

### ISSUE THREAD

**Issue by rvalitov** [v-zhuravlev/zbx_template_apache2#5]
Apache’s mod_status module provides a metric called requests/sec, but note that the name is a bit ambiguous—this value represents the average number of requests per second, calculated over the entire period the server has been running. Therefore, it will be difficult to detect sudden spikes or dips if your server has been running for a long time. To get a more meaningful metric, you need to  calculate the rate at which the number of requests has changed over a shorter time period. The same is true for the bytes per second metric.

**Comment by v-zhuravlev** [comment]
Thanks for the feedback. Will try to fix that. Please also note that this template will be incorporated into Zabbix 4.4 with your suggestions taken into account.

**Comment by v-zhuravlev** [comment]
Hello.

These Apache templates are now part of official Zabbix distribution with this issue fixed there, please use them instead if you have Zabbix 4.2 or later:

HTTP agent template:
https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/app/apache_http
Zabbix agent template:
https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/app/apache_agent
